name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.39.237.73 << 'EOF'
            cd ~/your-project-folder
            git pull origin main
            npm install
            npm run build
            pm2 reload healiary || pm2 start npm --name healiary -- start
          EOF
